default:
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" "$CI_REGISTRY" --password-stdin

docker-build-master-aomenc:
  stage: build
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE:aomenc" . -f Dockerfile.aomenc
    - docker push "$CI_REGISTRY_IMAGE:aomenc"
  only:
    - master

docker-build-master-svt-av1:
  stage: build
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE:svt-av1" . -f Dockerfile.svtav1
    - docker push "$CI_REGISTRY_IMAGE:svt-av1"
  only:
    - master

docker-build-master-rav1e:
  stage: build
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE:rav1e" . -f Dockerfile.rav1e  
    - docker push "$CI_REGISTRY_IMAGE:rav1e"
  only:
    - master

docker-build-master:
  stage: deploy
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE" .  
    - docker push "$CI_REGISTRY_IMAGE"
  only:
    - master
